"""initial schema

Revision ID: 2cf3afa55a9d
Revises: 
Create Date: 2026-09-08 05:27:21.910229

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf3afa55a9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tab_no', sa.String(length=64), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('territory', sa.String(length=255), nullable=True),
    sa.Column('department_1c', sa.String(length=255), nullable=True),
    sa.Column('position_1c', sa.String(length=255), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('experience_text', sa.String(length=128), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('rate_updated_at', sa.Date(), nullable=True),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tab_no', name='uq_emp_org_tab')
    )
    op.create_index(op.f('ix_employees_fio'), 'employees', ['fio'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_tab_no'), 'employees', ['tab_no'], unique=False)
    op.create_table('evaluation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_period_org_code')
    )
    op.create_index(op.f('ix_evaluation_periods_organization_id'), 'evaluation_periods', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('tab_no', sa.String(length=64), nullable=False),
    sa.Column('fio', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'admin_op', 'master', 'foreman', 'site_chief', name='userrole'), nullable=False),
    sa.Column('site_code', sa.String(length=64), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'tab_no', name='uq_user_org_tab')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tab_no'), 'users', ['tab_no'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=64), nullable=True),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.Column('position_fact', sa.String(length=255), nullable=True),
    sa.Column('worker_status', sa.String(length=64), nullable=True),
    sa.Column('shift_start', sa.Date(), nullable=True),
    sa.Column('last_final_score', sa.Float(), nullable=True),
    sa.Column('evaluate', sa.Boolean(), nullable=False),
    sa.Column('primary_user_id', sa.Integer(), nullable=True),
    sa.Column('dual_enabled', sa.Boolean(), nullable=False),
    sa.Column('secondary_user_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['secondary_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'employee_id', name='uq_assignment_period_emp')
    )
    op.create_index(op.f('ix_assignments_employee_id'), 'assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_assignments_evaluate'), 'assignments', ['evaluate'], unique=False)
    op.create_index(op.f('ix_assignments_organization_id'), 'assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_assignments_period_id'), 'assignments', ['period_id'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('original_user_id', sa.Integer(), nullable=False),
    sa.Column('substitute_user_id', sa.Integer(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['original_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.ForeignKeyConstraint(['substitute_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_organization_id'), 'delegations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_delegations_period_id'), 'delegations', ['period_id'], unique=False)
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_action'), 'domain_events', ['action'], unique=False)
    op.create_index(op.f('ix_domain_events_created_at'), 'domain_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_id'), 'domain_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_domain_events_entity_type'), 'domain_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_domain_events_organization_id'), 'domain_events', ['organization_id'], unique=False)
    op.create_table('production_coeffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('site_code', sa.String(length=64), nullable=True),
    sa.Column('coeff', sa.Float(), nullable=False),
    sa.Column('site_chief_user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['evaluation_periods.id'], ),
    sa.ForeignKeyConstraint(['site_chief_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_coeffs_organization_id'), 'production_coeffs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_production_coeffs_period_id'), 'production_coeffs', ['period_id'], unique=False)
    op.create_table('urgent_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_urgent_requests_employee_id'), 'urgent_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_urgent_requests_organization_id'), 'urgent_requests', ['organization_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('urgent_request_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_role', sa.Enum('admin', 'admin_op', 'master', 'foreman', 'site_chief', name='userrole'), nullable=False),
    sa.Column('score_quality', sa.Integer(), nullable=True),
    sa.Column('score_discipline', sa.Integer(), nullable=True),
    sa.Column('score_safety', sa.Integer(), nullable=True),
    sa.Column('score_skills', sa.Integer(), nullable=True),
    sa.Column('score_versatility', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', name='evaluationstatus'), nullable=False),
    sa.Column('client_mutation_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['urgent_request_id'], ['urgent_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_assignment_id'), 'evaluations', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_evaluations_client_mutation_id'), 'evaluations', ['client_mutation_id'], unique=False)
    op.create_index(op.f('ix_evaluations_employee_id'), 'evaluations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluator_id'), 'evaluations', ['evaluator_id'], unique=False)
    op.create_index(op.f('ix_evaluations_organization_id'), 'evaluations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evaluations_urgent_request_id'), 'evaluations', ['urgent_request_id'], unique=False)
    op.create_table('list_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_tickets_created_by_user_id'), 'list_tickets', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_list_tickets_organization_id'), 'list_tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_list_tickets_status'), 'list_tickets', ['status'], unique=False)
    op.create_table('urgent_evaluators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urgent_request_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['urgent_request_id'], ['urgent_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('urgent_request_id', 'user_id', name='uq_urgent_eval_user')
    )
    op.create_index(op.f('ix_urgent_evaluators_urgent_request_id'), 'urgent_evaluators', ['urgent_request_id'], unique=False)
    op.create_index(op.f('ix_urgent_evaluators_user_id'), 'urgent_evaluators', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urgent_evaluators_user_id'), table_name='urgent_evaluators')
    op.drop_index(op.f('ix_urgent_evaluators_urgent_request_id'), table_name='urgent_evaluators')
    op.drop_table('urgent_evaluators')
    op.drop_index(op.f('ix_list_tickets_status'), table_name='list_tickets')
    op.drop_index(op.f('ix_list_tickets_organization_id'), table_name='list_tickets')
    op.drop_index(op.f('ix_list_tickets_created_by_user_id'), table_name='list_tickets')
    op.drop_table('list_tickets')
    op.drop_index(op.f('ix_evaluations_urgent_request_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_organization_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluator_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_employee_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_client_mutation_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_assignment_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_urgent_requests_organization_id'), table_name='urgent_requests')
    op.drop_index(op.f('ix_urgent_requests_employee_id'), table_name='urgent_requests')
    op.drop_table('urgent_requests')
    op.drop_index(op.f('ix_production_coeffs_period_id'), table_name='production_coeffs')
    op.drop_index(op.f('ix_production_coeffs_organization_id'), table_name='production_coeffs')
    op.drop_table('production_coeffs')
    op.drop_index(op.f('ix_domain_events_organization_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_type'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_entity_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_created_at'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_action'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index(op.f('ix_delegations_period_id'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_organization_id'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_assignments_period_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_organization_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_evaluate'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_employee_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_tab_no'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_evaluation_periods_organization_id'), table_name='evaluation_periods')
    op.drop_table('evaluation_periods')
    op.drop_index(op.f('ix_employees_tab_no'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_fio'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###